import {
  ClerkProvider
} from '@clerk/nextjs'

import './globals.css'
import type { Metadata } from 'next'
 
import { DM_Sans } from 'next/font/google'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
const global_font = DM_Sans({
  subsets: ['latin'],
  weight: ['400','500', '700'], // Asegúrate de usar pesos válidos
})

export const metadata: Metadata = {
  title: 'Maintech',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
 
  
    <html lang="en">
      <ClerkProvider> 
        <body className={global_font.className}>
          <ConfettiProvider />
          <ToastProvider />
            {children}
        </body>
      </ClerkProvider>
    </html>
 
  )
}
